# Generated by Django 5.0.1 on 2024-02-14 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UTicket', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newuser',
            name='date_of_birth',
            field=models.DateField(null=True),
        ),
    ]
