# Generated by Django 5.0.1 on 2024-05-13 10:13

import UTicket.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UTicket', '0002_remove_tickets_id_alter_tickets_ticket_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='tickets',
            name='id',
            field=models.BigAutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tickets',
            name='ticket_number',
            field=models.CharField(default=UTicket.models.generate_short_ticket_id, max_length=10, unique=True),
        ),
    ]
