# Generated by Django 5.0.1 on 2024-02-14 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UTicket', '0003_remove_newuser_date_of_birth'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tickets',
            name='amount_of_passengers',
        ),
    ]
