# Generated by Django 5.0.1 on 2024-05-14 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UTicket', '0003_tickets_id_alter_tickets_ticket_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='tickets',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
