# Generated by Django 5.0.1 on 2024-05-21 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UTicket', '0007_departure_alter_tickets_flight_departure'),
    ]

    operations = [
        migrations.DeleteModel(
            name='City',
        ),
        migrations.AlterField(
            model_name='tickets',
            name='flight_departure',
            field=models.TextField(max_length=40),
        ),
        migrations.AlterField(
            model_name='tickets',
            name='city_destination',
            field=models.TextField(max_length=40),
        ),
        migrations.AlterField(
            model_name='tickets',
            name='city_of_departure',
            field=models.TextField(max_length=40),
        ),
        migrations.AlterField(
            model_name='tickets',
            name='date_of_birth',
            field=models.TextField(max_length=10),
        ),
        migrations.AlterField(
            model_name='tickets',
            name='first_name',
            field=models.TextField(max_length=40),
        ),
        migrations.AlterField(
            model_name='tickets',
            name='phone_number',
            field=models.TextField(max_length=20),
        ),
        migrations.AlterField(
            model_name='tickets',
            name='plane_class',
            field=models.TextField(max_length=30),
        ),
        migrations.AlterField(
            model_name='tickets',
            name='plane_place',
            field=models.TextField(max_length=30),
        ),
        migrations.AlterField(
            model_name='tickets',
            name='return_date',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='tickets',
            name='second_name',
            field=models.TextField(max_length=40),
        ),
        migrations.DeleteModel(
            name='Departure',
        ),
    ]
