# Generated by Django 5.0.1 on 2024-05-17 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UTicket', '0007_departure_alter_tickets_flight_departure'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tickets',
            name='return_date',
        ),
        migrations.AlterField(
            model_name='departure',
            name='departure_time',
            field=models.DateField(),
        ),
    ]
