# Generated by Django 5.0.1 on 2024-05-17 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UTicket', '0008_remove_tickets_return_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='departure',
            name='name',
        ),
        migrations.AlterField(
            model_name='departure',
            name='departure_time',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='tickets',
            name='flight_departure',
            field=models.CharField(max_length=10),
        ),
    ]
