# Generated by Django 5.0.1 on 2024-05-17 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UTicket', '0009_remove_departure_name_alter_departure_departure_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tickets',
            name='city_destination',
            field=models.TextField(max_length=30),
        ),
        migrations.AlterField(
            model_name='tickets',
            name='city_of_departure',
            field=models.TextField(max_length=30),
        ),
        migrations.AlterField(
            model_name='tickets',
            name='date_of_birth',
            field=models.TextField(max_length=10),
        ),
        migrations.AlterField(
            model_name='tickets',
            name='first_name',
            field=models.TextField(max_length=40),
        ),
        migrations.AlterField(
            model_name='tickets',
            name='phone_number',
            field=models.TextField(max_length=20),
        ),
        migrations.AlterField(
            model_name='tickets',
            name='plane_class',
            field=models.TextField(max_length=30),
        ),
        migrations.AlterField(
            model_name='tickets',
            name='plane_place',
            field=models.TextField(max_length=30),
        ),
        migrations.AlterField(
            model_name='tickets',
            name='second_name',
            field=models.TextField(max_length=40),
        ),
    ]
