# Generated by Django 5.0.1 on 2024-05-28 12:02

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UTicket', '0010_remove_payment_billing_address_1_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='amount',
            new_name='price',
        ),
        migrations.AddField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='payment',
            name='token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='currency',
            field=models.CharField(default='UAH', max_length=3),
        ),
        migrations.AlterField(
            model_name='payment',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='payment',
            name='ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UTicket.tickets'),
        ),
        migrations.AlterField(
            model_name='tickets',
            name='return_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
