# Generated by Django 5.0.1 on 2024-05-24 10:56

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UTicket', '0010_remove_payment_billing_address_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
