# Generated by Django 5.0.1 on 2024-05-18 10:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UTicket', '0010_alter_tickets_city_destination_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tickets',
            name='city_destination',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destinations', to='UTicket.city'),
        ),
        migrations.AlterField(
            model_name='tickets',
            name='city_of_departure',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departures', to='UTicket.city'),
        ),
        migrations.AlterField(
            model_name='tickets',
            name='flight_departure',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UTicket.departure'),
        ),
    ]
