# Generated by Django 5.0.1 on 2024-05-31 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UTicket', '0011_rename_amount_payment_price_payment_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tickets',
            name='transport_type',
            field=models.CharField(default=1, max_length=5),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('Оплата в процесі', 'Pending'), ('Підтверджено', 'Confirmed'), ('Відхилено', 'Failed')], default='Оплата в процесі', max_length=20),
        ),
    ]
