# Generated by Django 5.0.1 on 2024-06-01 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UTicket', '0012_tickets_transport_type_alter_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='tickets',
            name='flight_return',
            field=models.CharField(default=1, max_length=40),
            preserve_default=False,
        ),
    ]
