# Generated by Django 5.0.1 on 2024-05-24 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UTicket', '0012_payment_price_payment_status_alter_payment_currency_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tickets',
            name='return_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
